# Generated by Django 5.2.3 on 2025-06-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commnent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnent',
            new_name='comment',
        ),
    ]
